AWSTemplateFormatVersion: 2010-09-09
Description: Template for the RDS database used by quay

Parameters:

  VpcId:
    Description: >-
      The VPC-scoped resources will belong to this VPC.
    Type: AWS::EC2::VPC::Id

  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-4]))$
    ConstraintDescription: >-
      CIDR block parameter must be in the form x.x.x.x/16-24.
    Description: >-
      CIDR block for VPC.
    Default: 10.0.0.0/16
    Type: String

  DBName:
    Default: "quay"
    Description: My database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  DBInstanceClass:
    Default: db.m5.large
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
    AllowedValues:
      - "db.m5.large"
      - "db.m5.xlarge"
      - "db.m5.2xlarge"

  DBAllocatedStorage:
    Default: '50'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.

  MaxAllocatedStorage:
    Default: '50'
    Description: The max size of the database (GiB)
    Type: Number
    MinValue: '50'
    MaxValue: '65536'

  DBBackupRetentionPeriod:
    Type: Number
    Default: 14

  DBUsername:
    NoEcho: 'true'
    Description: Username for postgres database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    NoEcho: 'true'
    Description: Password postgres database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Database Configuration"
        Parameters:
          - DBPassword
          - DBUsername
          - DBBackupRetentionPeriod
          - DBAllocatedStorage
          - DBInstanceClass
          - DBName
          - MaxAllocatedStorage
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcCidr

Resources:

  DatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: !Ref VpcCidr

  Database:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      #EnableIAMDatabaseAuthentication: !Ref EnableIAMDatabaseAuthentication
      #EngineVersion: !If [HasDBSnapshotIdentifier, !Ref 'AWS::NoValue', !Ref EngineVersion]
      EngineVersion: 10.4
      #KmsKeyId: !If [HasKmsKeyAndNotDBSnapshotIdentifier, {'Fn::ImportValue': !Sub '${ParentKmsKeyStack}-KeyId'}, !Ref 'AWS::NoValue']
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      #DBSnapshotIdentifier: !If [HasDBSnapshotIdentifier, !Ref DBSnapshotIdentifier, !Ref 'AWS::NoValue']
      MultiAZ: true
      #OptionGroupName: !If [HasDBOptionGroupName, !Ref DBOptionGroupName, !Ref 'AWS::NoValue']
      #PreferredBackupWindow: !Ref PreferredBackupWindow
      #PreferredMaintenanceWindow: "Sun:05:00-Sun:06:00"
      StorageType: gp2
      #StorageEncrypted: !If [HasDBSnapshotIdentifier, !Ref 'AWS::NoValue', !If [HasKmsKey, true, false]]
      VPCSecurityGroups:
      - !Ref DatabaseSecurityGroup
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: !Ref DBUsername
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      #MaxAllocatedStorage: !Ref MaxAllocatedStorage
      MasterUserPassword: !Ref DBPassword

#  DatabaseBurstBalanceTooLowAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database storage burst balance over last 10 minutes too low, expect a significant performance drop soon.'
#      ComparisonOperator: LessThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: BurstBalance
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 20
#  DatabaseCPUUtilizationTooHighAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database CPU utilization over last 10 minutes too high.'
#      ComparisonOperator: GreaterThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: CPUUtilization
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 80
#  DatabaseCPUCreditBalanceTooLowAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database CPU credit balance over last 10 minutes too low, expect a significant performance drop soon.'
#      ComparisonOperator: LessThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: CPUCreditBalance
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 20
#  DatabaseDiskQueueDepthTooHighAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database disk queue depth over last 10 minutes too high, performance may suffer.'
#      ComparisonOperator: GreaterThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: DiskQueueDepth
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 64
#  DatabaseFreeableMemoryTooLowAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database freeable memory over last 10 minutes too low, performance may suffer.'
#      ComparisonOperator: LessThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: FreeableMemory
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 64000000 # 64 Megabyte in Byte
#  DatabaseFreeStorageSpaceTooLowAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database free storage space over last 10 minutes too low.'
#      ComparisonOperator: LessThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: FreeStorageSpace
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 2000000000 # 2 Gigabyte in Byte
#  DatabaseSwapUsageTooHighAlarm:
#    Condition: HasAlertTopic
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      AlarmDescription: 'Average database swap usage over last 10 minutes too high, performance may suffer.'
#      ComparisonOperator: GreaterThanThreshold
#      Dimensions:
#      - Name: DBInstanceIdentifier
#        Value: !Ref DBInstance
#      EvaluationPeriods: 1
#      MetricName: SwapUsage
#      Namespace: 'AWS/RDS'
#      OKActions:
#      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      Period: 600
#      Statistic: Average
#      Threshold: 256000000 # 256 Megabyte in Byte
#  DatabaseEventSubscription:
#    Condition: HasAlertTopic
#    Type: 'AWS::RDS::EventSubscription'
#    Properties:
#      EventCategories:
#      - failover
#      - failure
#      - 'low storage'
#      - maintenance
#      - 'read replica'
#      - recovery
#      SnsTopicArn: {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
#      SourceIds: [!Ref DBInstance]
#      SourceType: 'db-instance'
