AWSTemplateFormatVersion: 2010-09-09
Description: Template for Quay on RHEL HA

Parameters:

  VpcId:
    Description: >-
      The VPC-scoped resources will belong to this VPC.
    Type: AWS::EC2::VPC::Id

  RHELAmi:
    Description: >-
      Current Red Hat Enterprise Linux AMI to use.
    Type: AWS::EC2::Image::Id

  KeyName:
    Description: >-
      EC2 key pair name
    Type: String

  Quay0Subnet:
    Description: >-
      The subnet to launch the first quay node into.
    Type: AWS::EC2::Subnet::Id

  Quay1Subnet:
    Description: >-
      The subnet to launch the second quay node into.
    Type: AWS::EC2::Subnet::Id

  Quay2Subnet:
    Description: >-
      The subnet to launch the third quay node into.
    Type: AWS::EC2::Subnet::Id

  QuaySecurityGroupId:
    Description: >-
      The quay security group ID.
    Type: AWS::EC2::SecurityGroup::Id

#  QuayInstanceProfileName:
#    Description: >-
#      IAM profile to associate with quay nodes.
#    Type: String

  QuayInstanceType:
    Default: m5.xlarge
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Host Information"
        Parameters:
          - QuayInstanceType
          - RHELAmi
          - QuaySecurityGroupId
          #- QuayInstanceProfileName
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - Quay0Subnet
          - Quay1Subnet
          - Quay2Subnet
#      - Label:
#          default: "Load Balancer Automation"
#        Parameters:
#          - AutoRegisterELB
#          - RegisterNlbIpTargetsLambdaArn
#          - ExternalApiTargetGroupArn
#          - InternalApiTargetGroupArn
#          - InternalServiceTargetGroupArn
    ParameterLabels:
      VpcId:
        default: "VPC ID"
      Quay0Subnet:
        default: "Quay-0 Subnet"
      Quay1Subnet:
        default: "Quay-1 Subnet"
      Quay2Subnet:
        default: "Quay-2 Subnet"
      QuayInstanceType:
        default: "Quay Instance Type"
      #QuayInstanceProfileName:
      #  default: "Quay Instance Profile Name"
      RHELAmi:
        default: "Red Hat Enterprise Linux CoreOS AMI ID"
      QuaySecurityGroupId:
        default: "Quay Security Group ID"

#Conditions:
#  DoRegistration: !Equals ["yes", !Ref AutoRegisterELB]

Resources:
  Quay0:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref RHELAmi
      KeyName: !Ref KeyName
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: "50"
          VolumeType: "gp2"
      #IamInstanceProfile: !Ref QuayInstanceProfileName
      InstanceType: !Ref QuayInstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref "QuaySecurityGroupId"
          SubnetId: !Ref "Quay0Subnet"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo dnf -y update
            sudo dnf -y install podman vim firewalld python3
      Tags:
        - Key: Name
          Value: !Join ["-", ["quay", "0"]]

  Quay1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref RHELAmi
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: "50"
            VolumeType: "gp2"
      #IamInstanceProfile: !Ref QuayInstanceProfileName
      InstanceType: !Ref QuayInstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref "QuaySecurityGroupId"
          SubnetId: !Ref "Quay1Subnet"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo dnf -y update
            sudo dnf -y install podman vim firewalld python3
      Tags:
        - Key: Name
          Value: !Join ["-", ["quay", "1"]]

  Quay2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref RHELAmi
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: "50"
            VolumeType: "gp2"
      #IamInstanceProfile: !Ref QuayInstanceProfileName
      InstanceType: !Ref QuayInstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref "QuaySecurityGroupId"
          SubnetId: !Ref "Quay2Subnet"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo dnf -y update
            sudo dnf -y install podman vim firewalld python3
      Tags:
        - Key: Name
          Value: !Join ["-", ["quay", "2"]]

Outputs:

  Quay0PrivateIp:
    Description: The quay 0 node private IP address.
    Value: !GetAtt Quay0.PrivateIp

  Quay1PrivateIp:
    Description: The quay 1 node private IP address.
    Value: !GetAtt Quay1.PrivateIp

  Quay2PrivateIp:
    Description: The quay 2 node private IP address.
    Value: !GetAtt Quay2.PrivateIp
