---

- name: Create Alert Stack
  delegate_to: localhost
  amazon.aws.cloudformation:
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default(omit) }}"
    security_token: "{{ ansible_env.AWS_SESSION_TOKEN | default(omit) }}"
    region: "{{ ansible_env.AWS_DEFAULT_REGION | default(omit) }}"
    #ec2_url: "{{ cloudformation_endpoint | default(omit) }}"
    validate_certs: "{{ aws_ssl_enabled }}"
    stack_name: "quayalertstack"
    state: present
    disable_rollback: true
    create_timeout: 10
    template: "roles/aws/files/alerts.yaml"
    template_parameters:
      Email: "{{ email_address }}"
      FallbackEmail: "{{ fallback_email_address }}"
  register: alert_stack_outputs
  tags:
    - alert

