---

- name: Get RDS stack info
  delegate_to: localhost
  amazon.aws.cloudformation_info:
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default(omit) }}"
    security_token: "{{ ansible_env.AWS_SESSION_TOKEN | default(omit) }}"
    region: "{{ ansible_env.AWS_DEFAULT_REGION | default(omit) }}"
    #ec2_url: "{{ cloudformation_endpoint | default(omit) }}"
    validate_certs: "{{ aws_ssl_enabled }}"
    stack_name: "{{ rds_stack_name }}"
    stack_resources: true
  register: rds_stack_outputs

- name: Set postgresql facts
  set_fact:
    postgresql_hostname: "{{ rds_stack_outputs.cloudformation.quayrds.stack_outputs.EndpointAddress }}"
    postgresql_port: "{{ rds_stack_outputs.cloudformation.quayrds.stack_outputs.EndpointPort }}"

