---

- name: Set overcommit kernel parameter in sysctl
  become: true
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-redis.conf

- name: Disable transparent huge pages
  become: true
  shell: "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"

- name: Create user systemd service location
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Start redis container
  containers.podman.podman_container:
    name: redis
    image: "{{ redis_image }}"
    state: created
    restart: true
    restart_policy: "always"
    ports:
      - "6379:6379"
    env:
      REDIS_PASSWORD: "{{ redis_password }}"
    generate_systemd:
      path: "{{ ansible_env.HOME }}/.config/systemd/user"
      restart_policy: always
      time: 120
      names: true
      container_prefix: container

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    state: started
    enabled: true
    name: container-redis
