---

- name: Create quay directories 
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "ec2-user"
    group: "ec2-user"
    mode: 0750
  loop:
    - "{{ quay_root_dir }}"
    - "{{ quay_root_dir }}/config"
    - "{{ quay_root_dir }}/storage"
    - "{{ ansible_env.HOME }}/.config/systemd/user"

- name: Allow quay to access a privileged port in sysctl
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '443'
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-quay.conf

- name: Copy quay template in place
  template:
    src: config.yaml.j2
    dest: "{{ quay_root_dir }}/config/config.yaml"

- name: Install postgres modules
  become: true
  package:
    name: "python3-psycopg2"
    state: present

- name: Enable pg_trgm postgres extension
  community.postgresql.postgresql_ext:
    login_host: "{{ postgresql_hostname }}"
    login_password: "{{ postgresql_password }}"
    login_user: "{{ postgresql_user }}"
    name: "pg_trgm"
    db: "{{ postgresql_db }}"
    state: present
  run_once: true

- name: Start quay
  containers.podman.podman_container:
    name: quay
    image: "{{ quay_image }}"
    state: started
    restart: true
    restart_policy: "always"
#    command: "repomirror"
#    sysctl:
#      net.core.somaxconn: 4096
    ports:
#      - "8080:8080"
      - "{{ quay_https_port }}:8443"
    volume:
      - "{{ quay_root_dir }}/config:/conf/stack:Z"
      - "{{ quay_root_dir }}/storage:/datastorage:Z"
    generate_systemd:
      path: "{{ ansible_env.HOME }}/.config/systemd/user"
      restart_policy: always
      time: 120
      names: true
      container_prefix: container
  tags:
    - quay

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    state: started
    enabled: true
    name: container-redis
