---

- name: Set overcommit
  become: true
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-redis.conf

- name: Disable transparent huge pages
  become: true
  shell: "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"

- name: Start redis container
  containers.podman.podman_container:
    name: redis
    image: "{{ redis_image }}"
    state: created
    restart: true
    restart_policy: "always"
    ports:
      - "6379:6379"
    env:
      REDIS_PASSWORD: "{{ redis_password }}"
    generate_systemd:
      path: /tmp/
      restart_policy: always
      time: 120
      names: true
      container_prefix: container

#- name: Create redis systemd service file
#  command: >
#    podman generate systemd -n -f redis
#  args:
#    chdir: '/tmp/'

- name: Write redis systemd unit file
  become: true
  copy:
    src: '/tmp/container-redis.service'
    dest: '/usr/lib/systemd/user/container-redis.service'
    remote_src: true

- name: Remove temp unit file
  file:
    path: '/tmp/container-redis.service'
    state: absent

- name: Force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    scope: global

- name: Ensure redis is started
  ansible.builtin.systemd:
    scope: global
    state: started
    name: container-redis
