---

- name: Make clair working directory
  become: true
  file:
    path: "/etc/clairv4/config"
    state: directory
    mode: "0755"

- name: Deploy clair config
  become: true
  template:
    src: templates/clairv4-config.j2
    dest: "/etc/clairv4/config/config.yaml"
    mode: "0644"

#- name: Copy the quay certificate into clair
#  copy:
#    remote_src: true
#    src: "{{ quay_root_dir }}/config/ssl.cert"
#    dest: "{{ quay_root_dir }}/clair/clair.crt"
#  when: CLAIR_ENCRYPT

#- name: Copy the quay key into clair
#  copy:
#    remote_src: true
#    src: "{{ quay_root_dir }}/config/ssl.key"
#    dest: "{{ quay_root_dir }}/clair/clair.key"
#  when: CLAIR_ENCRYPT

#- name: "Check that ca certificate exists on quay host at {{ quay_root_dir }}/config/extra_ca_certs/ca.crt"
#  stat:
#    path: "{{ quay_root_dir }}/config/extra_ca_certs/ca.crt"
#  register: _ca_cert_exist

#- name: Fail if CA certificate doesn't exist
#  fail:
#    msg: "CA certificate not on host at {{ quay_root_dir }}/config/extra_ca_certs/ca.crt"
#  when: not _ca_cert_exist.stat.isreg

- name: Install postgres modules
  become: true
  package:
    name: "python3-psycopg2"
    state: present

- name: Create clair database
  community.postgresql.postgresql_db:
    login_host: "{{ postgresql_hostname }}"
    login_password: "{{ postgresql_password }}"
    login_user: "{{ postgresql_user }}"
    owner: "{{ postgresql_user }}"
    name: "clair"
    state: present
  run_once: true
#  command: >
#    podman exec -it postgresql-quay /bin/bash -c 'echo "CREATE DATABASE clair" | psql -U postgres'

#- name: Grant privileges on clair database to quay user
#  command: >
#    podman exec -it postgresql-quay /bin/bash -c 'echo "GRANT ALL PRIVILEGES ON DATABASE clair TO quayuser" | psql -U postgres'

- name: Enable uuid-ossp postgres extension
  community.postgresql.postgresql_ext:
    login_host: "{{ postgresql_hostname }}"
    login_password: "{{ postgresql_password }}"
    login_user: "{{ postgresql_user }}"
    name: "uuid-ossp"
    db: "clair"
    state: present
  run_once: true
#  command: >
#    podman exec -it postgresql-quay /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"" | psql -d clair -U postgres'

- name: Create user systemd service location
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Start clair container
  containers.podman.podman_container:
    name: clair
    image: "{{ clair_image }}"
    state: created
    restart: true
    restart_policy: "always"
#    sysctl:
#      net.core.somaxconn: 4096
    env:
      CLAIR_CONF: '/clair/config.yaml'
      CLAIR_MODE: 'combo'
    ports:
      - "8080:8080"
      - "8089:8089"
    volume:
      - "/etc/clairv4/config:/clair"
    generate_systemd:
      path: "{{ ansible_env.HOME }}/.config/systemd/user"
      restart_policy: always
      time: 120
      names: true
      container_prefix: container

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    state: started
    enabled: true
    name: container-clair

- name: Wait for clair to start
  ansible.builtin.pause:
    seconds: 6
